### ISSUE TITLE
[Week1] JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by tmdgusya** [study-whiteship/study-whiteship#1]
- original link : https://github.com/whiteship/live-study/issues/1

**Comment by tmdgusya** [comment]
이번 Week1 내용을 통해서 Stack 에 대해 조금 더 잘알게 된것 같네요. 
Operand Stack 의 경우 Java ByteCode 를 보면 이해하기 쉬운것 같네요. 각 연산에 대한 Index 가 적혀있어서

**Comment by sallyjellyy** [comment]
분명 몇주전에 공부했던 내용인데도 헷갈리네요.. JVM 내용은 계속 반복해서 봐야할 것 같아요!

**Comment by sallyjellyy** [comment]
아 그리고 저 궁금한 게 있는데 클래스로더의 기능중 링킹부분에서 심볼림 메모리 참조라는 게 이해가 잘 안 가더라구요.. 혹시 잘 아시는 분 계시면 설명 부탁드리겠습니다 ㅎㅎ

**Comment by tmdgusya** [comment]
만약 아래와 같은 코드가 있고 그걸 바이트 코드화시키면

```java
if (obj.getClass() == String.class) {
    // do something
}
```
```
aload_1
invokevirtual   #21; //Method java/lang/Object.getClass:()Ljava/lang/Class;
ldc     #25; //class java/lang/String
if_acmpne       20
```
이렇게 나오는데 여기서 이제 ldc 라는 명령어를 해석해보면 이제 우리가 오늘 상수를 constant-pool 에 저장하는걸 배웠잖아요?
그 해당 constant-pool 에서 상수를 가져와서 상수의 참조 주소를 25번째 인덱스에 기록합니다. 
그니까 Symbolic 이란게 인덱스 25 번이 실제 String 상수를 가르키고 있어서 Symbolic memory 참조라고 하는것 같네요.

**Comment by tmdgusya** [comment]
## 예시코드 

```java
  1 public class Example {
  2
  3         public static void main(String[] args) {
  4                 String b =  "hello";
  5         }
  6
  7 }
```
## ByteCode
```
public class Example {
  public Example();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: ldc           #7                  // String hello
       2: astore_1
       3: return
}
```

여기서 `0: ldc           #7                  // String hello`  
부분에서 인덱스 7의 위치에(#7) 이제 상수 hello 의 참조 주소값을 저장하게 됩니다.

**Comment by polynomeer** [comment]
https://stackoverflow.com/questions/58434404/how-does-java-store-literals
roach와 비슷한 설명의 글이 있군요. 정말 별거 아니지만 놀라운 사실을 발견했습니다!
이미 아시는지는 모르겠지만, "hello"는 h로 시작하고 8번째 알파벳이라서 7번에 저장되네요.
"test string"이라는 문자열은 20번째인데 19번에 저장이 됩니다. ㅎㅎ
'어디에 hello가 있는지 어떻게 알지?'에 대한 답변은 대충 JVM은 '사전순으로 관리한다' 정도로 이해하면 되겠네요.

주의! 검증된 사실은 아닙니다. 우연의 일치일수도 있습니다!
https://docs.oracle.com/javase/specs/jvms/se8/html/

**Comment by tmdgusya** [comment]
> https://stackoverflow.com/questions/58434404/how-does-java-store-literals
> roach와 비슷한 설명의 글이 있군요. 정말 별거 아니지만 놀라운 사실을 발견했습니다!
> 이미 아시는지는 모르겠지만, "hello"는 h로 시작하고 8번째 알파벳이라서 7번에 저장되네요.
> "test string"이라는 문자열은 20번째인데 19번에 저장이 됩니다. ㅎㅎ
> '어디에 hello가 있는지 어떻게 알지?'에 대한 답변은 대충 JVM은 '사전순으로 관리한다' 정도로 이해하면 되겠네요.
> 
> 주의! 검증된 사실은 아닙니다. 우연의 일치일수도 있습니다!
> https://docs.oracle.com/javase/specs/jvms/se8/html/

아마도 hash 값을 알파벳 순서로 가지기에 그런게 아닐까요..? 그니까 hash(word) 하면 즉 뭐 어떤 값으로 해싱을 하는지는 몰라도
알파벳 순서와 연관된 크기를 가질것 같네요
