### ISSUE TITLE
[Week3] 연산자

### ISSUE THREAD

**Issue by polynomeer** [study-whiteship/study-whiteship#3]
https://github.com/whiteship/live-study/issues/3

**Comment by tmdgusya** [comment]
[instanceOf 속도에관한 흥미로운 글](https://stackoverflow.com/questions/103564/the-performance-impact-of-using-instanceof-in-java)

**Comment by tmdgusya** [comment]
https://stackoverflow.com/questions/29458676/how-to-avoid-instanceof-when-implementing-factory-design-pattern

instance of pattern 을 피하는 법입니다.

아까 August 가 올려주신 링크도 올려주시면 고마울것 같네요!~

**Comment by polynomeer** [comment]
기존의 switch문과 Java13의 `switch 연산자`는 다름을 명심합니다! 아래의 링크는 자바의 switch 표현의 발전에 관한 글입니다.
- https://mkyong.com/java/java-12-switch-expressions/
- https://mkyong.com/java/java-13-switch-expressions/
- https://docs.oracle.com/en/java/javase/13/language/switch-expressions.html
