### ISSUE TITLE
[Week4] 제어문

### ISSUE THREAD

**Issue by polynomeer** [study-whiteship/study-whiteship#4]
https://github.com/whiteship/live-study/issues/4

**Comment by sallyjellyy** [comment]
제어문 옵션 과제는., 저희도 옵션인가요..?

**Comment by polynomeer** [comment]
GitHub의 `Issue`는 앞으로 해당 주차 일요일까지는 열어두고 close 하도록 하겠습니다! 공유하고자 하는 추가 코멘트를 달아 주실 분들은 저기에 남겨주세요!

아, 그리고 앞으로도 optional 한 과제가 계속 있을 텐데, 기본 권장 사항은 모두 다 하는 것입니다. 하지만 저부터만 해도 시간에 쫓겨서 다 하지는 못하는 경우가 생기네요. 시간이 되면 다 하는 걸 목표로 하고, 못 하게 되면 필수과제라도 꼭 해서 완주하는 걸 목표로 합시다!

**Comment by polynomeer** [comment]
과제가 있는 주차의 이슈에만 `assignment` 라벨을 달아놓았습니다. 4주차, 5주차 말고는 과제가 없기 때문에 스터디가 끝나기 전에 한번이라도 다 해보는 것이 좋을 것 같습니다!
