### ISSUE TITLE
[Week7] 패키지

### ISSUE THREAD

**Issue by polynomeer** [study-whiteship/study-whiteship#7]
https://github.com/whiteship/live-study/issues/7

**Comment by tmdgusya** [comment]
이번장에서 왜 환경변수를 설정해주는지 이제 감이좀 잡히는것 같네요.

**Comment by polynomeer** [comment]
클래스패스(CLASSPATH)의 지정은 꽤나 중요한 부분인데, 직접 지정하는 것이 생각보다 쉽지않고 번거롭다는 것을 알게 되었습니다. 그래서 이번 학습이 IDE와 Maven이나 Gradle같은 빌드툴(또는 프로젝트 관리 툴)의 소중함을 알 수 있는 계기가 되었습니다. Gradle과 Maven에 대해서도 추가적인 학습이 필요하다는 것을 계속 느낍니다.
