### ISSUE TITLE
[Week8] 인터페이스

### ISSUE THREAD

**Issue by polynomeer** [study-whiteship/study-whiteship#8]
https://github.com/whiteship/live-study/issues/8

**Comment by tmdgusya** [comment]
개인적으로 우아한 querydsl 에서 공통적으로 implements 되는 부분들도 비용이다.. 라는 부분에서 좀 놀랐습니다.

내용적으로는 어렵지만 한번 보시고 생각해보셨으면 좋겠네요.

https://www.youtube.com/watch?v=zMAX7g6rO_Y&t=763s

**Comment by polynomeer** [comment]
자바8의 default 메소드와 static 메소드, 그리고 자바9의 private 메소드까지 정리할 수 있는 계기가 되었습니다. 참고링크에서 인터페이스 메소드의 발전에 대해서 잘 설명한 것 같아 공유합니다.
- https://howtodoinjava.com/java9/java9-private-interface-methods/
